---
title: "train_chol"
format: html
df-print: paged
---

# Setup

```{r}
#| label: setup

pacman::p_load(tidyverse, survey, srvyr, here, haven)

chol_ds <- read_sav(here("train_chol", "NHMS 2019 hyperchol_training.sav")) %>% 
  mutate_if(is.labelled, ~as_factor(.)) %>% 
#  mutate_if(is.labelled, ~zap_label(.)) %>% 
  mutate(one = 1)

chol_ds
```

# Design

```{r}
chol_design <- svydesign(id = ~EBID, strata = ~State_St, nest = T,
                         weights = ~WtFinal_NCD, data = chol_ds)

chol_design_srvyr <- chol_ds %>% 
  as_survey_design(ids = EBID, strata = State_St, nest = T, 
                   weights = WtFinal_NCD)

```

# Analysis

```{r}
svymean(~Overall_Chol, chol_design, na.rm = T) 

svytotal(~Overall_Chol, chol_design, na.rm = T) 

chol_design_srvyr %>%
  drop_na(Overall_Chol) %>% 
  group_by(Overall_Chol) %>%
  summarize(n_unw = unweighted(n()),
            proportion = survey_mean(vartype = c("se", "ci", "cv"), deff = T),
            total = survey_total(vartype = c("se", "ci", "cv"), deff = T))


chol_design_srvyr %>%
  drop_na(Overall_Chol) %>% 
  group_by(sex, Overall_Chol) %>%
  summarize(n_unw = unweighted(n()),
            proportion = survey_mean(vartype = c("se", "ci", "cv"), deff = T),
            total = survey_total(vartype = c("se", "ci", "cv"), deff = T))

chol_design_srvyr %>%
  drop_na(Overall_Chol) %>% 
  group_by(state, Overall_Chol) %>%
  summarize(n_unw = unweighted(n()),
            proportion = survey_mean(vartype = c("se", "ci", "cv"), deff = T),
            total = survey_total(vartype = c("se", "ci", "cv"), deff = T))

```


# Subpopulation

```{r}
dsub <- subset(chol_design, Overall_Chol == "Yes")

svymean(~sex, design = dsub, deff = T)

```

