---
title: "Recap Session 1"
subtitle: "Kursus R: Pengenalan dan Praktikal (Sesi 2)"
format: 
  clean-revealjs: 
    slide-number: true
    lightbox: true
    auto-stretch: false
    footer: "Recap Previous Session "
author:
  - name: Mohd Azmi Bin Suliman
    orcid: 0000-0002-2125-3811
    email: azmi.suliman@moh.gov.my
    affiliations: Pusat Penyelidikan Penyakit Tak Berjangkit, Institut Kesihatan Umum
date: 2024-03-06
date-format: "dddd, DD MMMM YYYY"
embed-resources: true
execute: 
  echo: true
---

# Recap Session 1

```{r}
#| label: setup
#| echo: false

pacman::p_load(tidyverse, kableExtra)
```

## Recap Session 1

-   Session 1: Introduction

```{r}
#| echo: false

tibble(Topic = c("R", 
                 "RStudio",
                 "Project (I)", 
                 "Project (II)", 
                 "Quarto"), 
       "Explaination/Example" = c("A programming languange for statistical computing and graphic", 
                                  "An IDE for R", 
                                  "'Container' for R project",
                                  "Always start with blank slate, save everything in notebook", 
                                  "Publishing system, but used for Notebook")) %>% 
  mutate(No = row_number(), .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```

## Recap Session 1

-   Session 1: Introduction

```{r}
#| echo: false

tibble(Topic = c("Object in R", 
                 "Data Modes", 
                 "Data Structure",
                 "Operators", 
                 "Functions"), 
       "Explaination/Example" = c("Almost everything in R is an object", 
                                  "Numeric, Character, Logical", 
                                  "value, vector, list, matrix, DATA FRAME", 
                                  "Arithmetic (+-), Assignment (<-), Relational (>=), Special (%>%)", 
                                  "Command to perform specific task, e.g. sqrt(4)")) %>% 
  mutate(No = row_number()+5, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```

## Recap Session 1

-   Session 1: Introduction

```{r}
#| echo: false

tibble(Topic = c("Packages",
                 "Data Wrangling", 
                 "Tidyverse (I)", 
                 "Tidyverse (II)"), 
       "Explaination/Example" = c("Set of functions and data. Can be installed and loaded",
                                  "Data cleaning and transformation activities", 
                                  "Collection of Packages with 'tidy' philosophy", 
                                  "mutate() for new variable and %>% pipe operator")) %>% 
  mutate(No = row_number()+10, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```

## Recap Session 2

-   Basic Statistical Test

```{r}
#| echo: false

tibble(Topic = c("`summarytools`",
                 "`freq()`", 
                 "`descr()`", 
                 "`group_by()", 
                 "`dfSummary()`"), 
       "Explaination/Example" = c("Packages used for descriptive statistics",
                                  "Frequency table for categorical variable", 
                                  "Univariate statistics for numerical variable", 
                                  "Grouping data for specific analysis", 
                                  "Data frame summary")) %>% 
  mutate(No = row_number(), .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```


## Recap Session 2

-   Basic Statistical Test

```{r}
#| echo: false

tibble(Topic = c("`gtsummary`",
                 "`tbl_summary()`", 
                 "`add_p()`", 
                 "`add_differences()`"), 
       "Explaination/Example" = c("Packages used for table",
                                  "Descriptive statistics", 
                                  "Statistical tests", 
                                  "Add differences")) %>% 
  mutate(No = row_number()+5, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```



## Recap Session 2

-   Basic Statistical Test

```{r}
#| echo: false

tibble(Topic = c("Contigency Table", 
                 "Pearson's Chi-square Test",
                 "Fisher's Exact Test", 
                 "McNemar's Test"), 
       "Explaination/Example" = c("with(data, table(var1, var2))", 
                                  "with(data, table(var1, var2)) %>% 
                                  chisq.test(correct = F)", 
                                  "with(data, table(var1, var2)) %>% 
                                  fisher.test()", 
                                  "with(data, table(var_pre, var_post)) %>% 
                                  mcnemar.test()")) %>% 
  mutate(No = row_number()+9, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```



## Recap Session 2

-   Basic Statistical Test

```{r}
#| echo: false

tibble(Topic = c("Welch's T-Test", 
                 "Paired T-Test", 
                 "One-way ANOVA", 
                 "Pearson's Correlation"), 
       "Explaination/Example" = c("t.test(dv ~ group, data)", 
                                  "t.test(Pair(var_post, var_pre) ~ 1, data", 
                                  "oneway.test(dv ~ group, data)", 
                                  "cor.test(~ var1 + var2, data, method = 'pearson')")) %>% 
  mutate(No = row_number()+13, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```



## Recap Session 2

-   Basic Statistical Test

```{r}
#| echo: false

tibble(Topic = c("Linear Regression", 
                 "tbl_uvregression(method = lm)",
                 "Logistic Regression",
                 "tbl_uvregression", 
                 "tbl_regression"), 
       "Explaination/Example" = c("lm(dv ~ iv1 + iv2, data)", 
                                  "data %>% tbl_uvregression(method = lm, y = dv, include = c(iv1, iv2))", 
                                  "glm(dv ~ iv1 + iv2, data, family = binomial)",
                                  "data %>% tbl_uvregression(method = glm, method.args = list(family = binomial), y = dv, include = c(iv1, iv2))", 
                                  "tbl_regression(model)")) %>%
  mutate(No = row_number()+17, .before = Topic) %>% 
  kbl() %>% 
  kable_classic()
```

